### ISSUE TITLE
InfluxDB upgrade

### ISSUE THREAD

**Issue by garamaleki** [krakendio/krakend-opencensus#45]
Hi

I have influxdb v2 installed which uses a different concept compared to v1.x (like bucket instead of db and token instead of username/pass). seemingly krakend exporter does not support this version. 

can you add support for newer versions of influxdb?

Thanks.

**Comment by kpacha** [comment]
please, check my comment on this issue: https://github.com/devopsfaith/krakend-ce/issues/293#issuecomment-828623183

**Comment by alombarte** [comment]
Specific instructions for Influx2: https://www.krakend.io/docs/telemetry/influxdb/#influx-v2
