### ISSUE TITLE
Mention the required B3 propagation style for datadog exports in the docs

### ISSUE THREAD

**Issue by igin** [krakendio/krakend-opencensus#69]
When integrating krakend into our datadog service landscape using the datadog exporter we had issues connecting the krakend spans to the spans of other services. After digging through the code we found that opencensus module uses B3 style propagation headers while the rest of our services (which do tracing through the standard datadog ddtrace-run) use datadog specific propagation headers. This leads to the fact that our krakend traces do show up in datadog but are not connected to the frontend and backend traces. 

Recently ddtrace-run introduced an option to support B3 style propagation using the environment variables `DD_TRACE_PROPAGATION_STYLE_EXTRACT` and `DD_TRACE_PROPAGATION_STYLE_INJECT` (see https://ddtrace.readthedocs.io/en/stable/configuration.html). To simplify the process for others I would suggest adding this information to the docs. 

Even better would of course be to support the datadog style but that seems like a larger issue.

**Comment by kpacha** [comment]
nice! the task has been added to the backlog.

Thanks for the suggestion

**Comment by alombarte** [comment]
Thank you @igin for your suggestion. Your comments have been added to the docs, it's a good addition.
You can see it online here: https://www.krakend.io/docs/telemetry/datadog/

If you think more modifications are needed please let me know.

**Comment by igin** [comment]
Awesome! Thanks for the quick response and implementation!

**Comment by arman-ashrafian** [comment]
FYI the env vars mentioned above and in the krakend docs are for the Python library (dd-trace-py). 

For nodejs (dd-trace-js) you can either set `DD_TRACE_EXPERIMENTAL_B3_ENABLED` environment variable or set up your tracer with `options.experimental.b3` set to true

source: https://github.com/DataDog/dd-trace-js/blob/7fb068aff5a877360e968523935811832ae7a75f/packages/dd-trace/src/config.js#L192

**Comment by kpacha** [comment]
@alombarte do you think this is something we should add to the documentation? Should I create a new issue on the documentation repo?
