### ISSUE TITLE
Datadog exporter deprecated

### ISSUE THREAD

**Issue by benjaminpottier** [krakendio/krakend-opencensus#77]
The https://pkg.go.dev/github.com/DataDog/opencensus-go-exporter-datadog exporter is deprecated. Is there anything planned for moving to using https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter ?

**Comment by kpacha** [comment]
OT is not fully stable yet (https://opentelemetry.io/docs/instrumentation/go/#status-and-releases), so we are waiting. We think is safer to stick with a lib in maintenance mode than to switch to a lib in beta stage.

Swapping to OT is in the backlog, we are just waiting for a 100% stable implementation.
